language: node_js
# nodejs版本
node_js: 
    - '8'

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install

before_script:
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run build

after_script:
  - rm -rf site-repo
  - git config user.name "${GIT_NAME}"
  - git config user.email "${GIT_EMAIL}"
  - git clone https://${SITE_REPO} site-repo && cd site-repo
  - mkdir -p ${BRANCH} && rm -rf ${BRANCH}/*
  - cp -r ../docs/.vuepress/dist ./${BRANCH}/
  - git add .
  - git commit -am "Auto Build"
  - git push --force --quiet "https://${SITE_PUSH_TOKEN}@${SITE_REPO}" master
# E: Build LifeCycle

#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    - /^incubating-.*$/
